Update app template
saleor/saleor-app-klaviyo pull request #24
Opened 2022-10-04 09:13 UTC by lkostrowski

- Update dependencies
- Add readme and getting started
- Add Instructions section
- Add default metric names placesholders
- Add dark mode support

2022-10-04 09:49 UTC, peelar commented on docs/connect-with-klaviyo.md
> +Follow [readme](../README.md) and deploy app. Then, install it in your Saleor Dashobard
```suggestion
Follow the [README](../README.md) and deploy the app. Then, install it in your Saleor Dashboard.
```

2022-10-04 09:49 UTC, peelar commented on docs/connect-with-klaviyo.md
> +# These are basic steps to connect App with your Klavio app
```suggestion
# How to connect your App with Klavio
```

2022-10-04 09:49 UTC, peelar commented on docs/connect-with-klaviyo.md
> +## Install app
```suggestion
## Installation
```

2022-10-04 09:49 UTC, peelar commented on docs/connect-with-klaviyo.md
> +Naturally you need Klaviyo access - you can sign up [here](https://www.klaviyo.com/)
```suggestion
Before we continue, you need a Klaviyo account. You can sign up [here](https://www.klaviyo.com/).
```

2022-10-04 09:49 UTC, peelar commented on docs/connect-with-klaviyo.md
> +## Create Klaviyo account
```suggestion
## Creating Klaviyo account
```

2022-10-04 09:49 UTC, peelar commented on docs/connect-with-klaviyo.md
> +## Get your public key
```suggestion
## Accessing your public key
```

2022-10-04 09:49 UTC, peelar commented on docs/connect-with-klaviyo.md
> +Follow this [Klaviyo document](https://help.klaviyo.com/hc/en-us/articles/115005062267-How-to-Manage-Your-Account-s-API-Keys), to find your public key
```suggestion
To access your public key, please follow this [Klaviyo document](https://help.klaviyo.com/hc/en-us/articles/115005062267-How-to-Manage-Your-Account-s-API-Keys).
```

2022-10-04 09:49 UTC, peelar commented on docs/connect-with-klaviyo.md
> +## Configure app in Dashboard
```suggestion
## Dashboard configuration
```

2022-10-04 09:49 UTC, peelar commented on docs/connect-with-klaviyo.md
> +3. Paste public key into the input field and save
```suggestion
1. Open Dashboard and navigate to the "Apps" section.
2. Find your fresh installed Klaviyo app.
3. Paste your public key into the input field and save.
```

2022-10-04 09:49 UTC, peelar commented on docs/connect-with-klaviyo.md
> +## Trigger initial webhook
```suggestion
## Triggering the initial webhook
```

2022-10-04 09:49 UTC, peelar commented on docs/connect-with-klaviyo.md
> +Your Metric should be visible on the list
```suggestion
First and foremost, you need to perform an initial API call to Klaviyo, which will create a metric (of which the name you can configure in the Klaviyo App configuration screen).

Let's navigate to "Customers" and create the first, dummy customer.

Then, open Klavio [Metrics page](https://www.klaviyo.com/analytics/metrics).

Your Metric should be visible on the list:
```

2022-10-04 09:49 UTC, peelar commented on docs/connect-with-klaviyo.md
> +## Create flow
```suggestion
## Creating a flow
```

2022-10-04 09:49 UTC, peelar commented on docs/connect-with-klaviyo.md
> +5. Now you can proceed creating your flow. Feel free to welcome your user!![](readme-assets/flow-screen.png)
```suggestion
1. Open the [flow creation page](https://www.klaviyo.com/flows/create).
2. Click "Create from scratch" and name your flow.
[](readme-assets/flow-creation.png)
3. Create a new trigger with "Metric".
[](readme-assets/trigger-setup.png)
4. Your freshly sent Metric should be available.
[](readme-assets/trigger-metric.png)
5. Now you can proceed to create your flow. Feel free to welcome your user.
[](readme-assets/flow-screen.png)
```

2022-10-04 12:19 UTC, peelar approved these changes

2022-10-05 10:13 UTC, krzysztofwolski requested changes
Besides change in the readme LGTM

2022-10-05 10:13 UTC, krzysztofwolski commented on README.md
> +- [node version XX](http://nodejs.com)
XX was intended to be filled... :D

2022-10-05 11:04 UTC, lkostrowski commented on README.md
> +- [node version XX](http://nodejs.com)
tldr :D

2022-10-05 11:08 UTC, krzysztofwolski approved these changes

2022-10-05 11:35 UTC, merged